ga_parameters:
  cxpb: 0.5
  mutpb: 0.5
  bloat_limit: 17
curriculum:
  warmup: 10000
  ramp_span: 150
weights_main_easy:
  core_family: 0.4
  core_given: 0.4
  core_title: 0.05
  core_suffix: 0.05
  core_gender: 0.05
  bonus_exact: 0.05
  bonus_coverage: 0.03
  bonus_uncertainty: 0.02
  penalty_hallucination: 0.05
  penalty_vital: 0.1
  penalty_lazy: 0.05
gates_main_easy:
  min_family: 0.0
  min_given: 0.0
  max_penalty: 0.0
weights_main_strict:
  core_family: 0.297
  core_given: 0.297
  core_title: 0.143
  core_suffix: 0.063
  core_gender: 0.05
  bonus_exact: 0.1
  bonus_coverage: 0.05
  bonus_uncertainty: 0.02
  penalty_hallucination: 0.2
  penalty_vital: 0.4
  penalty_lazy: 0.3
gates_main_strict:
  min_family: 0.3
  min_given: 0.3
  max_penalty: 2.0
weights_detail:
  core_family: 0.25
  core_given: 0.25
  core_title: 0.05
  core_suffix: 0.05
  core_gender: 0.05
  bonus_exact: 0.05
  bonus_coverage: 0.3
  bonus_uncertainty: 0.03
  penalty_hallucination: 0.1
  penalty_vital: 0.2
  penalty_lazy: 0.15
gates_detail:
  min_family: 0.3
  min_given: 0.3
  max_penalty: 2.0
weights_structure:
  core_family: 0.25
  core_given: 0.25
  core_title: 0.25
  core_suffix: 0.1
  core_gender: 0.1
  bonus_exact: 0.05
  bonus_coverage: 0.05
  bonus_uncertainty: 0.02
  penalty_hallucination: 0.1
  penalty_vital: 0.2
  penalty_lazy: 0.15
gates_structure:
  min_family: 0.3
  min_given: 0.3
  max_penalty: 2.0
